export const getAnalyticsData = async () => {
    try {
        
    } catch (error) {
        console.log("error in getAnalyticsData", error);
        throw new Error("Internal server error");
    }
}